apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
